version: '3'
networks:
  backnet:  
    name: backnet
volumes:
  mongodb_data:
  images:

services:
  db:
    image: db:latest
    container_name: db
    restart: always
    build: ./db
    networks:
      - backnet
    volumes:
      - mongodb_data:/data/db

  backend:
    image: backend:latest
    container_name: backend
    restart: always
    build: .
    depends_on:
      - db
    networks:
      - backnet
    volumes:
      - images:/app/images

  frontend:
    image: frontend:latest
    container_name: frontend
    restart: always
    build: ../ancient_rome_in_britain_frontend
    networks:
      - backnet

  proxy:
    image: proxy:latest
    container_name: proxy
    restart: always
    build: ./proxy
    depends_on:
      - backend
      - frontend
    networks:
      - backnet
    ports:
      - "443:443"
